### ISSUE TITLE
An empty MiningSchema is a deviation from the PMML standard

### ISSUE THREAD

**Issue by afard** [jpmml/jpmml-model#35] opened 2022-04-08 16:55 UTC
First, I am a big fan of the JPMML project, and I'm excited to observe its growth during the last years.

Recently, I tried jpmml-sklearn to convert an XGB model to its PMML format. Following, I add the Python script. I noticed that some of the tree models have an empty MiningSchema. An empty MiningSchema is a deviation from the PMML standard.
Here is the format of MiningSchema specified by the standard (https://dmg.org/pmml/v4-4-1/MiningSchema.html):

```xml
<xs:element name="MiningSchema">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Extension" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element maxOccurs="unbounded" ref="MiningField"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
```

Based on XML Schema guideline, the default value of minOccurs is 1 (https://www.w3.org/TR/xmlschema-0/#:~:text=The%20default%20value%20for%20both,not%20occur%20more%20than%20once.). Therefor, a MiningSchema must have at least one MiningField. We may file an issue on the Github page of JPMML.

It is correct that the tree models with empty MiningSchema have only a root node (no use of any input field), but they could still have defined MiningFields. In other words, a model can have defined inputs that are not used inside the model for prediction. To best of my understanding, a model as a black box in the PMML standard cannot be without any inputs; regardless of the fact how those inputs are utilized.

# The Python script
```python
from sklearn import datasets
import pandas as pd
import xgboost as xgb

iris = datasets.load_iris()
print(iris.target_names)
print(iris.feature_names)
print(iris.data[0:5])
print(iris.target)

data=pd.DataFrame({
    'sepal length':iris.data[:,0],
    'sepal width':iris.data[:,1],
    'petal length':iris.data[:,2],
    'petal width':iris.data[:,3],
    'species':iris.target
})
data.head()
from sklearn.model_selection import train_test_split

X=data[['sepal length', 'sepal width', 'petal length', 'petal width']]  # Features
y=data['species']  # Labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 70% training and 30% test
clf=xgb.XGBClassifier()
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

from sklearn2pmml import sklearn2pmml, make_pmml_pipeline
pmml_obj = make_pmml_pipeline(clf)  
sklearn2pmml(pmml_obj,"xgb_iris.xml")
print("Model exported as PMML successfully.Filename: xgb_iris.xml " )
```

**Comment by vruusmann** [comment] 2022-04-08 17:16
> I noticed that some of the tree models have an empty MiningSchema.

It's typically an indication of an over-fitted model. For example, when you're building a booster-style ensemble model, and specify an unreasonably large `n_estimators` value, then XGBoost typically resorts to "stuffing" the ensemble with empty decision trees until the `n_estimators` criterion is met.

An empty `MiningSchema` indicates a "data science problem", and shouldn't be ignored.

> An empty MiningSchema is a deviation from the PMML standard.

Yes, it's a JPMML extension to the PMML standard:
https://github.com/jpmml/jpmml-model/commit/b30a7d757a95693d391a8d55eadcd61a1e743901

Getting this stuff there was hard work!

If you look at the generated `org.dmg.pmml.MiningSchema` class source code, then you will find that this extension is properly marked with an `@org.jpmml.model.annotations.Optional(org.dmg.pmml.Version.XPMML)` annotation.

> Based on XML Schema guideline, the default value of minOccurs is 1

Yes, but I would argue that it's a mistake to make such a requirement (minOccurs > 1).

The JPMML relaxation does not invalidate the PMML specification in any way - all "canonical" PMML documents are 100% supported by the JPMML-Model library (and any other JPMML library along the stack).

> To best of my understanding, a model as a black box in the PMML standard cannot be without any inputs; regardless of the fact how those inputs are utilized.

Then how would you implement a constant-prediction model?

What makes the following regression model illegal? Why can't it be represented in PMML?
```xml
<RegressionModel>
  <MiningSchema/>
  <RegressionTable intercept="3.14"/>
</RegressionModel>
```

BTW, what do you expet the JPMML-XGBoost library to do when the user passes it an XGBoost model object that contains empty decision trees? Should the SkLearn2PMML utility function throw an expection or something?

How would that situation be an improvement over the current situation?

**Comment by vruusmann** [comment] 2022-04-08 17:17
Closing as "works as intended".

**Closed by vruusmann** 2022-04-08 17:17 UTC

**Comment by afard** [comment] 2022-04-08 18:06
Thanks for your quick response.

First, I believe that a PMML producer should strictly follow the constraints of the standard. Otherwise, the whole purpose of the standard of being a shared medium among different producers and consumers would be compromised. IMHO, any extension should be solely made based on the guideline of the standard through the Extension element:
https://dmg.org/pmml/v4-4-1/GeneralStructure.html#xsdElement_Extension

In principal, a predictive model should identify its input field. In other words, a model that can be applied on any data is meaningless and misleading. Even a constant-prediction model must have MiningFields although they are not used by the model internally.

When the JPMML-XGBoost library receives an XGBoost model object that contains empty decision trees, I expect it to create TreeModel segments similar to what it does now, but instead of empty MiningSchema, having a MiningSchema with MiningFields from the higher level.

**Comment by vruusmann** [comment] 2022-04-08 18:40
> I believe that a PMML producer should strictly follow the constraints of the standard.

Talking about this JPMML extension specifically, then how does the empty `MiningSchema` element affect your application? What's the downside?

The extension is clearly labeled as such, and it only affects the JPMML library level.

If you validated the PMML document against the PMML XSD, then this extension would be easily caught and reported. Perhaps you should activate this in your application.

> IMHO, any extension should be solely made based on the guideline of the standard through the Extension element

Can you give me an example about how you'd represent a constant-prediction decision tree or regression model using the `Extension` element.

> In principal, a predictive model should identify its input field.

This predictive model does not take any input fields.

> A model that can be applied on any data is meaningless and misleading.

Is your example XGBoost model "meaningless and misleading" then?

The SkLearn2PMML converter is doing its best to convert your XGBoost model into PMML representation. Garbage in, garbage out.

> I expect it to create TreeModel segments similar to what it does now, but instead of an empty MiningSchema, having a MiningSchema with MiningFields comin from the higher level model, MiningModel in this case.

This decision tree model is not utilizing any of those inputs. Why should it declare them?

**Comment by afard** [comment] 2022-04-11 21:32
> > I believe that a PMML producer should strictly follow the constraints of the standard.
> 
> Talking about this JPMML extension specifically, then how does the empty `MiningSchema` element affect your application? What's the downside?

We don't really rely on JPMML for our work. We're adding support of PMML standard to Vertica database as both producer and consumer (https://www.vertica.com/docs/11.1.x/HTML/Content/Authoring/AnalyzingData/MachineLearning/UsingExternalModels/UsingPMML/UsingPMMLModels.htm).  Vertica provides a set of built-in distributed algorithms to train ML models on BigData. The trained models are archived in DB and can be used for in-DB scoring at scale. Nevertheless, Vertica users would be able to export these models to PMML to be used externally. Besides, the users would be able to import the PMML models they have trained externally into Vertica to enjoy its model management and scalable in-DB scoring.
We usually test our product against several third-party libraries, including JPMML, to make sure we have satisfied the promise of the standard of sharing models between PMML compliant applications.
We think JPMML is one of the most complete open source libraries. That's why we usually recommend it to our customers who want to bridge between their Python or R ML environment and Vertica. That said, we will feel better to know that JPMML fully complies with the standard.

> 
> The extension is clearly labeled as such, and it only affects the JPMML library level.
> 
> If you validated the PMML document against the PMML XSD, then this extension would be easily caught and reported. Perhaps you should activate this in your application.
> 
> > IMHO, any extension should be solely made based on the guideline of the standard through the Extension element
> 
> Can you give me an example about how you'd represent a constant-prediction decision tree or regression model using the `Extension` element.

IMHO, you don't really need it. You can just add one dummy MiningField.
In contrast, I suggest you make an extension element for `x-mathContext` instead of making it an attribute of the TreeModel element. It is another deviation from the standard, but I think it is not as critical as an empty MiningSchema because it is not about the dataflow inside multiple models.

> 
> > In principal, a predictive model should identify its input field.
> 
> This decision tree does not take any input fields.
> 
> > A model that can be applied on any data is meaningless and misleading.
> 
> Is your example XGBoost model "meaningless and misleading" then?

I'm afraid that there is a misunderstanding here! A tree in which the root node is a leaf (you call it a constant-prediction decision tree) is a valid model as far as its input fields are defined; regardless of the fact that the values of the inputs have no impact on its prediction. A model without defined inputs implies that it can be applied on any data with any dimension and data types which is not compatible with the definition of an ML model in PMML.

> 
> The SkLearn2PMML converter is doing its best to convert your XGBoost model into PMML representation. Garbage in, garbage out.
> 
> > I expect it to create TreeModel segments similar to what it does now, but instead of an empty MiningSchema, having a MiningSchema with MiningFields comin from the higher level model, MiningModel in this case.
> 
> This decision tree model is not utilizing any of those inputs. Why should it declare them?

Because it will comply with the PMML standard then. :)
