### ISSUE TITLE
Large `MapValues` elements are loaded very slowly in newer library versions

### ISSUE THREAD

**Issue by PavelZeger** [jpmml/jpmml-model#34] opened 2022-01-09 07:17 UTC
Hi, Villu.
We are trying to upgrade our Java service, that uses JPMML library, to Java 11 but encountered an issue with evaluation time after the upgrade. 

The application docker image: **openjdk:11-jre**
The _jpmml_ library version: **1.5.14** (also we've tried with *1.5.16*; we haven't tried _1.6.0_ because for upgrading to this version we need to refactor the code due to changes in this version)

The evaluation code:
```java
long startHandle = System.currentTimeMillis();  
byte[] pmmlFileContent = pmmlFile.getContent();
String uncompressedValue = new String(pmmlFileContent, StandardCharsets.UTF_8);  
StringInputStream source = new StringInputStream(uncompressedValue);  
Evaluator evaluator = new LoadingModelEvaluatorBuilder().load(source).build();  
optimizePmml(((ModelEvaluator<?>) evaluator).getPMML());  
  
try {  
    evaluator.verify();  
} catch (Exception e) {  
    errorLogger.reportError(INIT, LOAD, CRITICAL, String.format("PMML file %s is incorrect", pmmlFile.getName()));  
 throw e;  
}  
EvaluatorMetadata evaluatorMetadata = extractMetadataFields(evaluator, pmmlFile);  
PMMLEvaluatorContainer pmmlEvaluatorContainer = new PMMLEvaluatorContainer(evaluator, evaluatorMetadata);
```

The possible solution suggested by you as we've found:
[https://openscoring.io/blog/2019/02/28/jpmml_model_api_configuring_jaxb_dependency/](https://openscoring.io/blog/2019/02/28/jpmml_model_api_configuring_jaxb_dependency/)
[https://groups.google.com/g/jpmml/c/bLvhf3MIQp0/m/j9DHDRo4AQAJ](https://groups.google.com/g/jpmml/c/bLvhf3MIQp0/m/j9DHDRo4AQAJ)

> If the … Java/JVM does not provide built in JAXB runtime,  
> then perhaps it's possible to include an independent 3rd party JAXB  
> runtime into the project? The JPMML-Model project contains two modules  
> org.jpmml:pmml-model-metro and org.jpmml:pmml-model-moxy, which should  
> include a full runtime dependency of Glassfish Metro and EclipseLink  
> MOXy JAXB runtimes, respectively. I'd personally experiment with  
> depending on the org.jpmml:pmml-model-moxy module (instead of the  
> standard org.jpmml:pmml-model module), as EclipseLink as a third party  
> vendor might more flexible/less intrusive in their approach.
> 
> Also, it should be remembered that newer Java/JVM SE versions also do  
> not include JAXB runtime. However, using the suggested modules has got  
> things working for me on all Java SE 9, 10, 11 and 12 so far.

Unfortunately using the new dependency _-metro_ and the latest version rewuires change in the code that currently we cannot allow us to perform.

The another solution was to leave the current  pmml-evaluator  version and add explicitly JAXB dependencies:

```
<dependency>
    <groupId>org.jpmml</groupId>
    <artifactId>pmml-evaluator</artifactId>
    <version>1.5.14</version>
</dependency>
<dependency>
    <groupId>org.jpmml</groupId>
    <artifactId>pmml-evaluator-extension</artifactId>
    <version>1.5.14</version>
</dependency>
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.2</version>
</dependency>
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>javax.activation-api</artifactId>
    <version>1.2.0</version>
</dependency>
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.2</version>
</dependency>
```

This solution has lead to an increased evaluation time of PMML files (with Java 8 we have up to 5 ms average evaluation for each file):

```
2021-12-28 13:57:13,685 [pool-2-thread-5] INFO  [PriorityManagerImpl] Finished to handle the pmml [3100] file [25649] ms
2021-12-28 13:57:13,721 [pool-2-thread-8] INFO  [PriorityManagerImpl] Finished to handle the pmml [3300] file [25588] ms
2021-12-28 13:57:14,297 [pool-2-thread-11] INFO  [PriorityManagerImpl] Finished to handle the pmml [3400] file [15163] ms
2021-12-28 13:57:14,596 [pool-2-thread-7] INFO  [PriorityManagerImpl] Finished to handle the pmml [3200] file [25095] ms
2021-12-28 14:02:02,839 [pool-2-thread-4] INFO  [PriorityManagerImpl] Finished to handle the pmml [3102] file [312919] ms
2021-12-28 14:02:03,502 [pool-2-thread-12] INFO  [PriorityManagerImpl] Finished to handle the pmml [3302] file [315177] ms
2021-12-28 14:02:04,817 [pool-2-thread-6] INFO  [PriorityManagerImpl] Finished to handle the pmml [3402] file [313270] ms
2021-12-28 14:02:09,896 [pool-2-thread-8] INFO  [PriorityManagerImpl] Finished to handle the pmml [3202] file [295978] ms
```

Upgrading the dependency as described on GitHub page ([https://github.com/jpmml/jpmml-evaluator](https://github.com/jpmml/jpmml-evaluator)) leads to the same evaluation time:

```
2021-12-28 14:43:59,059 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 1794766 size to pmml file 3300
2021-12-28 14:43:59,100 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 1198828 size to pmml file 3100
2021-12-28 14:43:59,102 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 1737901 size to pmml file 3102
2021-12-28 14:43:59,332 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 2085889 size to pmml file 3302
2021-12-28 14:43:59,656 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 10188345 size to pmml file 3400
2021-12-28 14:43:59,734 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 6968065 size to pmml file 21191331
2021-12-28 14:43:59,845 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 6280020 size to pmml file 61331
2021-12-28 14:43:59,932 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 11274487 size to pmml file 20691331
2021-12-28 14:44:00,031 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 10969208 size to pmml file 21391331
2021-12-28 14:44:00,080 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 5387857 size to pmml file 21291331
2021-12-28 14:44:00,147 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 15703073 size to pmml file 3200
2021-12-28 14:44:00,297 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 16025233 size to pmml file 3402
2021-12-28 14:44:00,499 [async-channel-group-0-handler-executor] INFO  [PmmlGridFsDao] Loaded 21234942 size to pmml file 3202
2021-12-28 14:44:20,477 [pool-2-thread-2] INFO  [PriorityManagerImpl] Finished to handle the pmml [3100] file [21374] ms
2021-12-28 14:44:20,514 [pool-2-thread-4] INFO  [PriorityManagerImpl] Finished to handle the pmml [3300] file [21431] ms
2021-12-28 14:44:21,143 [pool-2-thread-10] INFO  [PriorityManagerImpl] Finished to handle the pmml [3400] file [21486] ms
2021-12-28 14:44:21,440 [pool-2-thread-1] INFO  [PriorityManagerImpl] Finished to handle the pmml [3200] file [21292] ms
2021-12-28 14:49:23,238 [pool-2-thread-11] INFO  [PriorityManagerImpl] Finished to handle the pmml [3302] file [323904] ms
2021-12-28 14:49:24,054 [pool-2-thread-3] INFO  [PriorityManagerImpl] Finished to handle the pmml [3102] file [324951] ms
2021-12-28 14:49:26,909 [pool-2-thread-7] INFO  [PriorityManagerImpl] Finished to handle the pmml [3402] file [326611] ms
2021-12-28 14:49:30,200 [pool-2-thread-2] INFO  [PriorityManagerImpl] Finished to handle the pmml [3202] file [309723] ms
```

Upgrading to the version  _1.5.16_ gives the same result as described previously:

```
<dependency>
    <groupId>org.jpmml</groupId>
    <artifactId>pmml-evaluator-metro</artifactId>
    <version>1.5.16</version>
</dependency>
```
We'll appreciate if you could advise a solution for this issue.
Regards,
Pavel

**Comment by PavelZeger** [comment] 2022-01-11 10:33
Thank you!
I'll open an issue for JAXB also and can update my investigation results here if I'll find some helpful information for the community.

**Comment by vruusmann** [comment] 2022-01-11 10:44
> I'll open an issue for JAXB also

Be sure to prepare a solid example case first.

In my understanding, it affects the unmarshalling of elements whose child elements belong to two or more XML namespaces.

In the JPMML-Model case it's the `org.dmg.pmml.Row` element (not `MapValues`), which contains elements that belong to the JPMML-InlineTable namespaces:
```xml
<InlineTable xmlns="http://www.dmg.org/PMML-4_4" xmlns:data="http://jpmml.org/jpmml-model/InlineTable">
	<row>
		<data:input>PSLOCAL</data:input>
		<data:output>PUBLIC</data:output>
	</row>
</InlineTable>
```

I wonder if the performance regression is resolved if the `data:` prefix is simply deleted (it makes the PMML document incorrect, but would give the first data point).

**Comment by vruusmann** [comment] 2022-01-11 10:47
In addition to the `MapValues` element, the (possibly-) problematic `InlineTable/row` element is also used in many other places.

For example, if the model has been enriched with model verification data, then there's another `InlineTable` element in play - and this table may be rather big sometimes.

**Comment by PavelZeger** [comment] 2022-02-01 11:55
Hi.
I've found the reason of loading PMML files more than a hour.

In our staging environment we are using 3d party library for tracking exceptions and errors ([OverOps](https://www.overops.com)). 
Our Docker images have an old version of this agent (deployed as *.jar and *.so files). Unfortunately upgrading this agent to the version _4.59.1_, where Java 11 issue was fixed, still caused to loading time of 5-6 minutes instead of 1.5 minutes as we expected, and only upgrading to the lates version of their jar finally fixed the issue ([OverOps previous versions](https://doc.overops.com/docs/previous-versions)).

Also as a part of the solution I was need to fix the classpath with following dependencies (when we still use the version 1.5.14 of _jpmml_):
```xml
<dependency>  
	<groupId>com.sun.xml.ws</groupId>  
	<artifactId>jaxws-ri</artifactId>  
	<version>2.3.2</version>  
	<type>pom</type>  
</dependency>  
<dependency>  
	<groupId>javax.xml.bind</groupId>  
	<artifactId>jaxb-api</artifactId>  
	<version>2.3.0</version>  
</dependency>
```

We'll try to upgrade our old PMML files (with our custom regression model) to the version 4.4, to reduce large `MapValues` and will use the latest _jpmml_ library version - I've seen the load time improvements of up to 15% in general for all types of PMML files we have when I've upgraded to 1.6.1.

Thank you for your help!

**Comment by vruusmann** [comment] 2022-02-01 12:32
> Our Docker images have an old version of this agent

Interesting observation - loading performance may differ between "bare" and "agent-modified" JVM instances.

As mentioned above, I do recall this issue being a thing before you reported it. I wonder if these earlier complainers were also using JVM agents.

> Also as a part of the solution I was need to fix the classpath with following dependencies

The `com.sun.xml.ws:jaxws-ri` dependency is totally strange in the JPMML(-Model) context (because this is a local library, which does not do any web services networking).

The `javax.xml.bind:jaxb-api` dependency should already be included (I assume `-runtime` includes `-api` all by itself, otherwise GitHub Actions CI builds would fail for JDK 9 and newer):
https://github.com/jpmml/jpmml-model/blob/1.5.14/pom.xml#L171-L175
https://github.com/jpmml/jpmml-model/blob/1.5.14/pmml-model-metro/pom.xml#L32-L35

Right now, you're simply downgrading my 2.3.3 version to 2.3.0.

> I've seen the load time improvements of up to 15% in general for all types of PMML files we have when I've upgraded to 1.6.1

The 1.6.X version removed the `org.dmg.pmml.FieldName` class (an enum-like thing for managing singleton field names). I wouldn't be surprised if it was the `FieldName#create(String)` factory method that alone consumed these 15% of CPU cycles.

**Comment by vruusmann** [comment] 2022-02-01 12:34
Another idea - is the performance penalty specific to the GlassFish Metro JAXB runtime, or does it affect the EclipseLink MOXy JAXB runtime as well?

I shall create a PMML document with 1M-row `MapValues` element, and find out.

**Comment by PavelZeger** [comment] 2022-02-01 16:36
> Right now, you're simply downgrading my 2.3.3 version to 2.3.0.

I'll fix it. It's a working attempt to "freeze" the current service in a stable state before refactoring and prevent compilation errors.

Currently the classpath has the following dependencies:
```
jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.jar
com/sun/xml/ws/jaxws-rt/2.3.2/jaxws-rt-2.3.2.jar
org/glassfish/jaxb/jaxb-runtime/2.3.1/jaxb-runtime-2.3.1.jar
org/glassfish/jaxb/txw2/2.3.1/txw2-2.3.1.jar
com/sun/istack/istack-commons-runtime/3.0.7/istack-commons-runtime-3.0.7.jar
javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar
com/sun/xml/ws/policy/2.7.6/policy-2.7.6.jar
org/glassfish/gmbal/gmbal/4.0.0/gmbal-4.0.0.jar
org/glassfish/external/management-api/3.2.1/management-api-3.2.1.jar
org/glassfish/pfl/pfl-basic/4.0.1/pfl-basic-4.0.1.jar
org/glassfish/pfl/pfl-tf/4.0.1/pfl-tf-4.0.1.jar
org/glassfish/pfl/pfl-asm/4.0.1/pfl-asm-4.0.1.jar
org/glassfish/pfl/pfl-dynamic/4.0.1/pfl-dynamic-4.0.1.jar
org/glassfish/pfl/pfl-basic-tools/4.0.1/pfl-basic-tools-4.0.1.jar
org/glassfish/pfl/pfl-tf-tools/4.0.1/pfl-tf-tools-4.0.1.jar
org/jvnet/staxex/stax-ex/1.8.1/stax-ex-1.8.1.jar
com/sun/xml/stream/buffer/streambuffer/1.5.7/streambuffer-1.5.7.jar
org/jvnet/mimepull/mimepull/1.9.10/mimepull-1.9.10.jar
com/sun/xml/fastinfoset/FastInfoset/1.2.16/FastInfoset-1.2.16.jar
org/glassfish/ha/ha-api/3.1.12/ha-api-3.1.12.jar
com/sun/xml/messaging/saaj/saaj-impl/1.5.0/saaj-impl-1.5.0.jar
javax/xml/soap/javax.xml.soap-api/1.4.0/javax.xml.soap-api-1.4.0.jar
jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar
com/sun/xml/ws/jaxws-tools/2.3.2/jaxws-tools-2.3.2.jar
com/sun/xml/bind/jaxb-xjc/2.3.2/jaxb-xjc-2.3.2.jar
com/sun/xml/bind/jaxb-jxc/2.3.2/jaxb-jxc-2.3.2.jar
com/sun/xml/ws/jaxws-eclipselink-plugin/2.3.2/jaxws-eclipselink-plugin-2.3.2.jar
jakarta/mail/jakarta.mail-api/1.6.3/jakarta.mail-api-1.6.3.jar
jakarta/persistence/jakarta.persistence-api/2.2.2/jakarta.persistence-api-2.2.2.jar
org/eclipse/persistence/org.eclipse.persistence.moxy/2.7.4/org.eclipse.persistence.moxy-2.7.4.jar
org/eclipse/persistence/org.eclipse.persistence.core/2.7.4/org.eclipse.persistence.core-2.7.4.jar
org/eclipse/persistence/org.eclipse.persistence.asm/2.7.4/org.eclipse.persistence.asm-2.7.4.jar
com/sun/xml/ws/sdo-eclipselink-plugin/2.3.2/sdo-eclipselink-plugin-2.3.2.jar
org/eclipse/persistence/org.eclipse.persistence.sdo/2.7.4/org.eclipse.persistence.sdo-2.7.4.jar
org/eclipse/persistence/commonj.sdo/2.1.1/commonj.sdo-2.1.1.jar
jakarta/xml/ws/jakarta.xml.ws-api/2.3.2/jakarta.xml.ws-api-2.3.2.jar
jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar
jakarta/xml/soap/jakarta.xml.soap-api/1.4.1/jakarta.xml.soap-api-1.4.1.jar
jakarta/jws/jakarta.jws-api/1.1.1/jakarta.jws-api-1.1.1.jar
javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar
org/jpmml/pmml-evaluator/1.5.14/pmml-evaluator-1.5.14.jar
org/jpmml/pmml-model/1.5.14/pmml-model-1.5.14.jar
org/jpmml/pmml-agent/1.5.14/pmml-agent-1.5.14.jar
org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar
org/jpmml/pmml-evaluator-extension/1.5.14/pmml-evaluator-extension-1.5.14.jar
```


> I wouldn't be surprised if it was the `FieldName#create(String)`
> factory method that alone consumed these 15% of CPU cycles.

Yes. The legacy code includes this implementation.

**Comment by vruusmann** [comment] 2022-02-04 08:57
I've created a small demo application [MapValuesExample.java](https://github.com/jpmml/jpmml-model/files/8001337/MapValuesExample.java.txt) that marshals/unmarshals a `MapValues` element with 1M rows.

After re-building, this application is run both with GlassFish Metro and EclipseLink MOXy JAXB runtimes:
```
$JAVA_HOME/bin/java -Djakarta.xml.bind.JAXBContextFactory=org.glassfish.jaxb.runtime.v2.ContextFactory -cp pmml-model-example/target/pmml-model-example-executable-1.6-SNAPSHOT.jar org.jpmml.model.example.MapValuesExample
$JAVA_HOME/bin/java -Djakarta.xml.bind.JAXBContextFactory=org.eclipse.persistence.jaxb.JAXBContextFactory -cp pmml-model-example/target/pmml-model-example-executable-1.6-SNAPSHOT.jar org.jpmml.model.example.MapValuesExample
```

The PMML file size is ~125 MB, and my 7-year old laptop is able to marshal it in ~3 seconds and unmarshal in ~5 seconds. This claim holds true for all Java (1.)8, Java 11 and Java 17.

This is way better performance than expected (translates to ~200k rows/second unmarshalling speed).

The problem must be related to the application code that uses the JPMML-Model library (or its JVM configuration - see the above discussion about the relevance of Java agents).

@PavelZeger Does your PMML document contain `MapValues` element(s) with a combined number of >10M rows?

**Comment by PavelZeger** [comment] 2022-02-06 11:08
The answer I've gotten from the DS team:

> The entire PMML files are with ~200k rows, so there are no such MapValues

Probably the problem is buried within the code that need to be refactored including continues upgrading of libraries.

**Comment by vruusmann** [comment] 2022-02-06 11:54
Maybe this `MapValues` loading issue affects the (late end of the-) 1.5.X development branch only?

I haven't tested my small demo application with the `1.5.16` version.

This issue definitely doesn't exist in the 1.6.X development branch (at the time of testing, the latest version being the `1.6.2` version). Maybe it was solved automagically when switching from Java XML binding (`javax.xml.bind`) to Jakarta XML Binding (`jakarta.xml.bind`).

It's probably time to close this issue as "invalid" and/or "not reproducible". Can be re-opened anytime when there's a clear well-isolated example (targeting the 1.6.X development branch!) available.

**Closed by vruusmann** 2022-02-06 11:54 UTC
